// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChGmJCiu-TXnHBnQ55FELHj0GO8YpF1Gg',
    appId: '1:1070409855681:web:7d3d5dcb52e5de1de29a40',
    messagingSenderId: '1070409855681',
    projectId: 'yappingchatapp',
    authDomain: 'yappingchatapp.firebaseapp.com',
    storageBucket: 'yappingchatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfrpdHMWM74XCEEHXrL-y7PEWk75WnsbE',
    appId: '1:1070409855681:android:32a41fb679860e29e29a40',
    messagingSenderId: '1070409855681',
    projectId: 'yappingchatapp',
    storageBucket: 'yappingchatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH_sTOMpCY789It6uY5AnLleNcZYjAMVg',
    appId: '1:1070409855681:ios:fccfab8c13ce1e5be29a40',
    messagingSenderId: '1070409855681',
    projectId: 'yappingchatapp',
    storageBucket: 'yappingchatapp.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH_sTOMpCY789It6uY5AnLleNcZYjAMVg',
    appId: '1:1070409855681:ios:fccfab8c13ce1e5be29a40',
    messagingSenderId: '1070409855681',
    projectId: 'yappingchatapp',
    storageBucket: 'yappingchatapp.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChGmJCiu-TXnHBnQ55FELHj0GO8YpF1Gg',
    appId: '1:1070409855681:web:ca8a2cef075a9b6fe29a40',
    messagingSenderId: '1070409855681',
    projectId: 'yappingchatapp',
    authDomain: 'yappingchatapp.firebaseapp.com',
    storageBucket: 'yappingchatapp.appspot.com',
  );
}
